name: Deploy to Cloud Run from Source

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: nft-generation-microservice
  SERVICE: warden-platform-backend
  REGION: asia-southeast1
  PRIVATE_KEY: -----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC3DwpE7SY1/zzu\ngRShecbw01UoWhk4usTLKadLeG//Ymb1iOd/v9clYDFWo20nUWPeCYGRVUf/hers\nMk//8LnKbMU6JJyy0e8mgOMM5GHzB9HtCLlpBGOTehk3RkunW2IbSpdUqN5j5ji7\nE+BvmuUHIUrDdLG92T8ICJQFLLt2N54KcRfnb1luga7ToSrEfEzTz7FQ/jEXAuSS\nAV6Il6IO43gRAQ/ZIXTPhuPWk6ZS+kfHnKLbWQ+fpU9tML6lTDF28K3q6tNRZdXj\nFsPC/IOgGfUfsTd7fZ1iNrIhuSPM+wkhpQ/ufLMOaV0WDby/pmZzof9FM9KQB+fA\nbsoz6SK5AgMBAAECggEAB17e6DsPNo3eF3FRkhXb5X7w1xTXnqHgghidgIurIMKG\nyDyYq5tfD4Vxvx4J61Ma3QoPcjlXkomDFbsJ3xGDfYvHHinyuD19LlTyr2Zzriwi\nrvNSudCALOQ15zSYn7atetFUSgeZmraekqPAfeXj8ldMEhYdAPqiD9H+mb29F4ug\nuGyEWrVoQJyUZ6MTURrFfT63P1eeCwqTehbsQakTnIn5bWK5veKjKED12xcOsYAM\n9iqgIb4wSFkIKM1F6tFjkE4iG5wIhQtqSgj4TlKMYlxKCxnGdOTIAqXTi2Mpk+Xk\naU4HNcoppvWQpEynzJiz3BDZTKEg15cRb0+wdF9NQQKBgQDuxrhOaa0qPpIYkgxq\n2VjIqoGIZeqAPvFU1rNEti+pY8aeJhwEJNJ4dXtq8NdGTLR1lGXlJF6T11KJA1Sm\n8BFj29PeYRqffeT1jNu7B//lQzapLitv6W/QqrRnvx8LN8XLfKTaJ4fc+Bh5brrs\nyrUZ2FMPe8eKhQHpGzk3TtO0oQKBgQDEQ26XdTIesVjGSDqBX90+W2TcuyoQY5b6\n/ZnJujeIv+oK5lgqqnLtCKlaxOeLNxJ6sfTQc5ghpsYgPesPbbMQxTj0I2AWne7P\np6yhbcz89kC1MRwTUsbRWzCuiHdqlFZ2gDaonONhDNwxpKBwhHoeqwExFJfFfMI6\nFEGBVD0fGQKBgBQVEptFuBK9gHwgjHrQHO+Dp7FZIQf4Q0Pnatx0lj2g7quOePzA\nPBN1jhPIfdKj0OmyuX80N+AnVAHCDfScbFoBuygQ8rRHWmJsnm50lckqhgZko7Kd\n55GdSd8P7AR9hF1A9nyCpqKnGyfbcE1KH0E1OIcs2fOEjEyWxZEpSBUBAoGBAIRp\nFhi66biJX+JOYqJcQdDLKk49O9DYz8jABdxydPset1DpPPx0CJtgp5lklO54llAO\n9aMZCb9SXALuo0LCePfMh3M21qILpU2Vy0MR6CWWIevcmRt0Ukx2oG5wBVjzgS3r\nrHSvfDxCx9/6OIAQ8K72IhSx1v9W/1bdyZ/ubFopAoGAWvI8R/TolP98VfDjAZn8\n2RSgWIz3rwfcVISyKTnWFYJQore8O4iSYb06psyad33wWNHKLrGExW4UP6yCCO1c\nFnZrdgej8RTS3Y8GNMp5IA0LK1eqC3hFmVnVtSWhr3IyR+gDWSq5jOYrhwaLP27N\nzm2ZPHJt6hSLu/PcWXoTlYY=\n-----END PRIVATE KEY-----
  CLIENT_EMAIL: nft-generation@nft-generation-microservice.iam.gserviceaccount.com
  STORAGE_MEDIA_BUCKET: nft-generator-microservice-bucket-test
  JWT_SECRET_KEY: WARDEN
  HASH_SALT: 10
  HASHIDS_SALT: wardenthebest
  GUARD_PASSWORD: 1234
  MONGODB_URI: mongodb+srv://wardennftplatform:WardenNFT2022@cluster0.1sedrpx.mongodb.net/Warden?retryWrites=true&w=majority
  POLYGON_MUMBAI: https://rpc-mumbai.maticvigil.com/
  OTP_KEY: "1754736871936836"
  OTP_SECRETKEY: cae0862644ee0c89f95fa95f5487caea

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If required, update to the appropriate source folder
          source: ./
          env_vars: |
            PROJECT_ID=${{ env.PROJECT_ID }}
            PRIVATE_KEY=${{ env.PRIVATE_KEY }}
            CLIENT_EMAIL=${{ env.CLIENT_EMAIL }}
            STORAGE_MEDIA_BUCKET=${{ env.STORAGE_MEDIA_BUCKET }}
            JWT_SECRET_KEY=${{ env.JWT_SECRET_KEY }}
            HASH_SALT=${{ env.HASH_SALT }}
            HASHIDS_SALT=${{ env.HASHIDS_SALT }}
            GUARD_PASSWORD=${{ env.GUARD_PASSWORD }}
            MONGODB_URI=${{ env.MONGODB_URI }}
            POLYGON_MUMBAI=${{ env.POLYGON_MUMBAI }}
            OTP_KEY=${{ env.OTP_KEY }}
            OTP_SECRETKEY=${{ env.OTP_SECRETKEY }}

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
